name: Build CUDA library

on:
  # build on every push + PR; create a Release when a tag is pushed
  push:
    branches: [ master ]
    tags:     [ "v*.*.*" ]
  pull_request:

jobs:
  build:
    runs-on: windows-latest   # VS 2022 is pre-installed
    steps:
      - uses: actions/checkout@v4

      # Need to install the toolkit on the fly
      - name: Install CUDA
        uses: Jimver/cuda-toolkit@v0.2.25
        with:
          cuda: "12.9.0"        # any 12.x/11.x value works :contentReference[oaicite:0]{index=0}

      # Add MSBuild.exe to PATH (Visual Studio BuildTools)
      - uses: microsoft/setup-msbuild@v2   :contentReference[oaicite:1]{index=1}

      # Build invocation
      - name: Build via script
        shell: pwsh
        run: ./build-lib.ps1 -OutDir "${{github.workspace}}\artifacts"

      # Upload the built library
      - name: Compress artifacts
        run: Compress-Archive -Path artifacts\* -DestinationPath cuda-lib-win64.zip
        shell: pwsh

      - name: Upload zipped artifact
        uses: actions/upload-artifact@v4
        with:
          name: cuda-lib-win64
          path: cuda-lib-win64.zip

  # Create a GitHub Release whenever a tag is pushed
  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: cuda-lib-win64
          path: dist
      - name: Create GitHub release
        uses: softprops/action-gh-release@v2   :contentReference[oaicite:3]{index=3}
        with:
          files: dist/*
