name: Build CUDA library

on:
  # build on every push + PR; create a Release when a tag is pushed
  push:
    branches: [ master, ci_test ]
    tags:     [ "v*.*.*" ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest   # VS 2022 is pre-installed
    steps:
      - uses: actions/checkout@v4

      # Need to install the toolkit on the fly
      - name: Install CUDA
        uses: Jimver/cuda-toolkit@v0.2.24
        id: cuda-toolkit
        with:
          cuda: "12.9.0"

      # Add MSBuild.exe to PATH (Visual Studio BuildTools)
      - uses: microsoft/setup-msbuild@v2

      # Build invocation
      - name: Build via script
        shell: pwsh
        run: ./build_lib.ps1 -o "${{github.workspace}}\artifacts"

      # Upload the built library
      - name: Compress artifacts
        run: Compress-Archive -Path artifacts\* -DestinationPath cuda-lib-win64.zip
        shell: pwsh

      - name: Upload zipped artifact
        uses: actions/upload-artifact@v4
        with:
          name: cuda-lib-win64
          path: cuda-lib-win64.zip

  release:
    needs: build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: cuda-lib-win64
          path: dist
  
      - name: Create or update "latest" release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest Build
          files: dist/*
          prerelease: true       # Optional: mark it clearly as not a stable release
          make_latest: true      # Optional: this is now the "latest" release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

